spring.application.name=SmartResumeAnalyzer

#==== MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/resumedb



# Thymeleaf settings
spring.thymeleaf.cache=false

# OpenAI Settings
openai.api.key=YOUR_OPENAI_API_KEY
openai.model=gpt-4o-mini

# Azure OpenAI Configuration (optional if using OpenAI)
azure.openai.api.key=dummy_key
azure.openai.endpoint=dummy_endpoint
azure.openai.deployment.model.id=dummy_model_id
