spring.application.name=SmartResumeAnalyzer
server.port=${PORT:8080}

#==== MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://praveeniit202_db_user:xgr7GF5pCqimMYaA@cluster0.mz4c3nh.mongodb.net/resumedb?retryWrites=true&w=majority&appName=Cluster0}

# Thymeleaf settings
spring.thymeleaf.cache=false

# OpenAI Settings
openai.api.key=${OPENAI_API_KEY:YOUR_OPENAI_API_KEY}
openai.model=gpt-4o-mini


# Azure OpenAI Configuration (optional if using OpenAI)
azure.openai.api.key=${AZURE_OPENAI_API_KEY:dummy_key}
azure.openai.endpoint=${AZURE_OPENAI_ENDPOINT:dummy_endpoint}
azure.openai.deployment.model.id=${AZURE_OPENAI_MODEL_ID:dummy_model_id}

